package com.blockchaincafe.order.invoice.impl;

import com.blockchaincafe.order.invoice.InvoicePdfService;
import com.blockchaincafe.order.invoice.model.InvoiceData;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Service
public class InvoicePdfServiceImpl implements InvoicePdfService {

    private static final Path BASE_DIR = Paths.get("generated-invoices");

    @Override
    public Path generateInvoicePdf(InvoiceData invoiceData) {
        try {
            Files.createDirectories(BASE_DIR);

            Path output = getInvoicePath(invoiceData.getOrderId());

            try (PDDocument document = new PDDocument()) {
                PDPage page = new PDPage(PDRectangle.A4);
                document.addPage(page);

                try (PDPageContentStream content = new PDPageContentStream(document, page)) {
                    PDType1Font bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                    PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

                    float y = 780;
                    float left = 50;

                    content.beginText();
                    content.setFont(bold, 20);
                    content.newLineAtOffset(left, y);
                    content.showText("Blockchain Cafe Invoice");
                    content.endText();

                    y -= 40;

                    y = writeLine(content, bold, regular, left, y, "Invoice Number:", value(invoiceData.getInvoiceNumber()));
                    y = writeLine(content, bold, regular, left, y, "Order ID:", value(invoiceData.getOrderId()));
                    y = writeLine(content, bold, regular, left, y, "Payer Type:", value(invoiceData.getPayerType()));
                    y = writeLine(content, bold, regular, left, y, "Payment ID:", value(invoiceData.getPaymentId()));
                    y -= 10;

                    if (invoiceData.getCompanyName() != null) {
                        y = writeLine(content, bold, regular, left, y, "Company Name:", invoiceData.getCompanyName());
                    }

                    if (invoiceData.getVatId() != null) {
                        y = writeLine(content, bold, regular, left, y, "VAT ID:", invoiceData.getVatId());
                    }

                    y -= 20;
                    y = writeLine(content, bold, regular, left, y, "Gross Total:", "EUR " + invoiceData.getGrossTotal());
                    y = writeLine(content, bold, regular, left, y, "Net Total:", "EUR " + invoiceData.getNetTotal());
                    y = writeLine(content, bold, regular, left, y, "VAT Total:", "EUR " + invoiceData.getTotalVat());

                    y -= 30;

                    content.beginText();
                    content.setFont(regular, 11);
                    content.newLineAtOffset(left, y);
                    content.showText("This invoice was generated by Blockchain Cafe prototype.");
                    content.endText();
                }

                document.save(output.toFile());
            }

            return output;
        } catch (IOException e) {
            throw new RuntimeException("Failed to generate invoice PDF", e);
        }
    }

    @Override
    public Path getInvoicePath(String orderId) {
        return BASE_DIR.resolve(orderId + ".pdf");
    }

    private float writeLine(
            PDPageContentStream content,
            PDType1Font bold,
            PDType1Font regular,
            float left,
            float y,
            String label,
            String value
    ) throws IOException {
        content.beginText();
        content.setFont(bold, 12);
        content.newLineAtOffset(left, y);
        content.showText(label);
        content.endText();

        content.beginText();
        content.setFont(regular, 12);
        content.newLineAtOffset(left + 140, y);
        content.showText(value);
        content.endText();

        return y - 22;
    }

    private String value(String input) {
        return input == null ? "-" : input;
    }
}
