server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://mysql:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
