server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
	
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Origin "";

    location / {
        try_files $uri $uri/ /index.html;
    }

   location /api/products {
    proxy_pass http://menu-service:8082/api/products;
}

        location /api/orders {
        proxy_pass http://order-service:8083/api/orders;
    }
    location /api/invoices {
        proxy_pass http://order-service:8083/api/invoices;
    }

    location /api/nfc/status {
    proxy_pass http://nfc-bridge-service:8088;
}

    location /api/payments {
        proxy_pass http://payment-service:8084;
    }

    location /api/wallets {
        proxy_pass http://wallet-service:8085;
    }

    location /api/vat {
        proxy_pass http://vat-service:8086;
    }

    location /api/blockchain {
        proxy_pass http://blockchain-service:8087;
    }

    location /api/nfc/checkout-intent {

    proxy_pass http://nfc-bridge-service:8088/api/nfc/checkout-intent;

}

    location /api/nfc/pending {
    proxy_pass http://nfc-bridge-service:8088;
}

    location /api/nfc/last-resolution {
        proxy_pass http://nfc-bridge-service:8088;
    }

    location /api/nfc/tap-and-resolve {

    proxy_pass http://nfc-bridge-service:8088/api/nfc/tap-and-resolve;

}
}
